version: '3'
services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"  # Optional, if you want to connect to Postgres from your host machine

  airflow-webserver:
    image: apache/airflow:2.1.0
    command: ["bash", "-c", "/airflow-entrypoint.sh"]  # Run the script with bash
    volumes:
      - ./airflow-entrypoint.sh:/airflow-entrypoint.sh
      - ./dags:/usr/local/airflow/dags
      - ./sql:/usr/local/airflow/sql
    ports:
      - "8080:8080"
